Import('env')

objects = Split('ztest.c #lib/libzpool/libzpool-user.a #lib/libzfscommon/libzfscommon-user.a #lib/libnvpair/libnvpair-user.a #lib/libavl/libavl.a #lib/libumem/libumem.a #lib/libsolcompat/libsolcompat.a')
cpppath = Split('#lib/libavl/include #lib/libnvpair/include #lib/libumem/include #lib/libzfscommon/include #lib/libzpool/include #lib/libsolcompat/include')

libs = Split('m dl rt pthread z aio crypto tirpc')

linkflags = [flag for flag in env['LINKFLAGS'] if flag != '-s'] + ['-rdynamic']

env.Program('ztest', objects,
    CPPPATH = env['CPPPATH'] + cpppath,
    LIBS = libs,
    LINKFLAGS = linkflags)
env.Depends('ztest', '../zdb/zdb')
